name: Playwright Cucumber Tests
on:
  pull_request:
    branches: [ main, develop]
  schedule:
    - cron: '0 10 * * *'
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    - name: Install Cucumber
      run: npm install --save-dev @cucumber/cucumber
    - name: Run global file to get session login
      run: npx playwright test || true
    - name: Run automated testcase with cucumber
      run: npm test
      shell: bash
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        path: test-results/cucumber-report.*
      if: always()

